#!/usr/bin/env sh

# global settings
yabai -m config window_topmost on # Floating windows on top
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config window_placement             second_child
yabai -m config window_shadow                off
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# window opacity
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90


# general space settings
# yabai -m config layout                       bsp # spaces default to BSP
yabai -m config layout                       float # spaces default to float
yabai -m config top_padding                  30
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
# yabai -m config top_padding                  36
# yabai -m config bottom_padding               10
# yabai -m config left_padding                 10
# yabai -m config right_padding                10
# yabai -m config window_gap                   5

# Always float specific apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^SourceTree$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off

# refresh my Übersicht bar when required
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"ubersicht-widgets-Workspace-jsx\"'"
yabai -m signal --add event=window_created \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"ubersicht-widgets-Workspace-jsx\"'"
yabai -m signal --add event=window_destroyed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"ubersicht-widgets-Workspace-jsx\"'"
yabai -m signal --add event=window_moved \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"ubersicht-widgets-Workspace-jsx\"'"
yabai -m signal --add event=application_activated \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"ubersicht-widgets-Workspace-jsx\"'"

# start limelight
killall limelight &> /dev/null
/Users/nick/code/src/github.com/koekeishiya/limelight/bin/limelight &> /dev/null &

echo "yabai configuration loaded.."
